name: snarelang4
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
#  sdk: '>=2.8.1 <3.0.0'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  petitparser: '>=3.1.0'
  dart_midi: '>=1.0.1'
  logging: '>=0.11.4'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
